replicaCount: 2

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

fullNameOverride: ""

dependency:
  enabled: false
  required: false
  name: dependency-config
  data:
    FEATURE_FLAG: "enabled"

hooks:
  preUpgradeSleepSeconds: 0
