// generate-catalog reads all scenario.yaml files and writes ui/src/data/catalog.ts.
// Run: go run scripts/generate-catalog.go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type scenario struct {
	ID          string   `yaml:"id"`
	Title       string   `yaml:"title"`
	Description string   `yaml:"description"`
	Category    string   `yaml:"category"`
	Track       string   `yaml:"track"`
	Level       string   `yaml:"level"`
	Tags        []string `yaml:"tags"`
	Skip        bool     `yaml:"skip"`
	Chaos       struct {
		Steps []any `yaml:"steps"`
	} `yaml:"chaos"`
	Stages []any `yaml:"stages"`
	Checks []struct {
		Type      string `yaml:"type"`
		Namespace string `yaml:"namespace"`
		Name      string `yaml:"name"`
	} `yaml:"checks"`
}

type catalogEntry struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Category    string `json:"category"`
	Difficulty  string `json:"difficulty"`
	Track       string `json:"track"`
	Level       string `json:"level"`
	Description string `json:"description"`
	Target      string `json:"target"`
	Chaos       bool   `json:"chaos,omitempty"`
}

func levelToDifficulty(level string) string {
	switch level {
	case "L1":
		return "easy"
	case "L2":
		return "medium"
	default:
		return "hard"
	}
}

func deriveTarget(s scenario) string {
	if len(s.Checks) > 0 {
		c := s.Checks[0]
		switch c.Type {
		case "deployment-ready":
			return fmt.Sprintf("deployment/%s", c.Name)
		case "service-endpoints", "service-reachable":
			return fmt.Sprintf("service/%s", c.Name)
		case "helm-release":
			return fmt.Sprintf("release/%s", c.Name)
		case "argocd-app-healthy":
			return fmt.Sprintf("app/%s", c.Name)
		case "resource-exists":
			return fmt.Sprintf("%s/%s", c.Namespace, c.Name)
		case "command-succeeds":
			return c.Name
		}
	}
	return ""
}

func main() {
	scenariosDir := "scenarios"
	outputFile := "ui/src/data/catalog.ts"

	if len(os.Args) > 1 {
		scenariosDir = os.Args[1]
	}
	if len(os.Args) > 2 {
		outputFile = os.Args[2]
	}

	var entries []catalogEntry

	err := filepath.Walk(scenariosDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || info.Name() != "scenario.yaml" {
			return err
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}

		var s scenario
		if err := yaml.Unmarshal(data, &s); err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		if s.Skip {
			return nil
		}

		desc := strings.TrimSpace(s.Description)
		// Take first sentence or first 200 chars
		if idx := strings.Index(desc, "\n\n"); idx > 0 {
			desc = desc[:idx]
		}
		if len(desc) > 200 {
			desc = desc[:197] + "..."
		}

		entries = append(entries, catalogEntry{
			ID:          s.ID,
			Title:       s.Title,
			Category:    s.Category,
			Difficulty:  levelToDifficulty(s.Level),
			Track:       s.Track,
			Level:       s.Level,
			Description: desc,
			Target:      deriveTarget(s),
			Chaos:       len(s.Chaos.Steps) > 0,
		})

		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Category != entries[j].Category {
			return entries[i].Category < entries[j].Category
		}
		return entries[i].ID < entries[j].ID
	})

	// Generate TypeScript
	var sb strings.Builder

	sb.WriteString("// Auto-generated by: go run scripts/generate-catalog.go\n")
	sb.WriteString("// Do not edit manually — edit scenario.yaml files instead.\n\n")

	sb.WriteString(`export interface ScenarioMeta {
  id: string;
  title: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
  track: string;
  level: "L1" | "L2" | "L3" | "L4";
  description: string;
  target: string;
  chaos?: boolean;
}

export const CATEGORY_LABELS: Record<string, string> = {
  all: "All",
  kubernetes: "kubectl",
  helm: "Helm",
  argocd: "Argo CD",
  terraform: "Terraform",
  aws: "AWS",
};

export const TRACK_LABELS: Record<string, string> = {
  all: "All",
  workloads: "Workloads",
  troubleshooting: "Troubleshooting",
  networking: "Networking",
  storage: "Storage",
  "pod-security": "Pod Security",
  "runtime-security": "Runtime Security",
  "release-ops": "Release Ops",
  "platform-eng": "Platform Eng",
};

export const LEVEL_LABELS: Record<string, string> = {
  all: "All",
  L1: "L1 Fix",
  L2: "L2 Diagnose",
  L3: "L3 Judge",
  L4: "L4 Investigate",
};

`)

	sb.WriteString("export const SCENARIOS: ScenarioMeta[] = [\n")
	for _, e := range entries {
		j, _ := json.Marshal(e)
		sb.WriteString("  ")
		sb.Write(j)
		sb.WriteString(",\n")
	}
	sb.WriteString("];\n")

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d scenarios\n", outputFile, len(entries))
}
